version: '3.9'

services:
    express:
        build: diegootayza/eze
        container_name: express
        restart: always
        ports:
            - '4000:4000'
        deploy:
            resources:
                limits:
                    cpus: '0.80'
                    memory: 768M
                reservations:
                    cpus: '0.50'
                    memory: 256M
