version: '3'

services:
    express:
        build: .
        container_name: express
        restart: always
        ports:
            - '4000:4000'
        deploy:
        resources:
            limits:
                cpus: '0.90'
                memory: 768M
            reservations:
                cpus: '0.50'
                memory: 256M
